[package]
name = "rust_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.19.0"
sysinfo = "0.29.0"
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"